### ISSUE TITLE
Problem: Inventory CSVs contain invalid key "dandiarchive/dandiarchive/data/"

### ISSUE THREAD

**Issue by jwodder** [dandi/s3invsync#95]
While running `s3invsync` after merging #91, the program ended up crashing after about 15 minutes because one CSV file — [`154d0efd-a30e-4b8f-96f7-aee9f14a16f1.csv.gz`](https://dandiarchive.s3.amazonaws.com/dandiarchive/dandiarchive/data/154d0efd-a30e-4b8f-96f7-aee9f14a16f1.csv.gz) — happens to contain 1922 lines with a key of "dandiarchive/dandiarchive/data/", which is a directory and thus regarded as invalid by `s3invsync`.  Interestingly, listing the objects in `s3://dandiarchive/dandiarchive/dandiarchive/` just shows `.../data/` as a prefix rather than as a key in its own right.

Note that "dandiarchive/dandiarchive/data/" is the directory in the `dandiarchive` bucket under which the inventory CSV files are stored.  The inventory CSVs also happen to contain entries for both themselves and the inventory manifests.

CC @yarikoptic

**Comment by yarikoptic** [comment]
"fun"

- please inquire somewhere on AWS S3 support groups on how that could happen or what it means. Ideally we should not just ignore that.
- pragmatically I think we could ignore such entries... having size 0 (no information loss ;) )

**Comment by yarikoptic** [comment]
<details>
<summary>some exploration</summary> 

chatgpt told 

1. Manual Creation of "Folder-like" Objects
Some tools or user actions explicitly create an object with a key ending in / (e.g., `aws s3api put-object --bucket <bucket-name> --key "foldername/"`).
These "folder" objects are just zero-byte files with a name that ends with /. Users might create them manually or through automated tools.

...

Examine the Metadata: Check the metadata and versionId of the objects to see when and how they were created.

```
aws s3api head-object --bucket <bucket-name> --key "foldername/" --version-id <versionId>
```

so in our case we see

```
(dandisets-2) dandi@drogon:/mnt/backup/dandi$ aws s3api head-object --bucket dandiarchive --key "dandiarchive/dandiarchive/data/" --version-id T_OH5MESsVJ6jygdWfiJfQJ166fQ6kDx
{
    "AcceptRanges": "bytes",
    "LastModified": "2024-12-18T15:23:29+00:00",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "VersionId": "T_OH5MESsVJ6jygdWfiJfQJ166fQ6kDx",
    "ContentType": "application/octet-stream",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

which tells us nothing new ;)  

</details>

My take is that we should safely ignore those `data/` 0-sized keys since they carry no data and in general serve us no utility AFAIK.  But we should error out if we see any key ending with `/` but not having 0-size.

**Comment by yarikoptic** [comment]
*Why inventory, while preparing its updates, uploads those keys for `data/` "folder" -- do they serve any purpose?*

**Comment by jwodder** [comment]
@yarikoptic Well, you've demonstrated that `dandiarchive/dandiarchive/data/` is apparently a key in the bucket, so why shouldn't it be included in the inventory CSVs?  Or are you suggesting that the inventory-creation process is responsible for creating the key in the bucket and are asking why that is?

**Comment by yarikoptic** [comment]
yes, the latter -- I think it is *the inventory-creation process is responsible for creating the key in the bucket*

**Comment by jwodder** [comment]
Question posted on AWS re:Post: https://repost.aws/questions/QU0Q_kJcxLS5yUwgKoVnshOA/why-does-s3-inventory-service-create-inventory-data-key
